version: '{build}'

platform: x64

branches:
  only:
    - master
    - /^greenkeeper-.*$/

skip_tags: true

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.12.5
  GO111MODULE: off
  APM_TEST_PACKAGES: go-signature-statusbar go-debug

  matrix:
    - ATOM_CHANNEL: stable
    - ATOM_CHANNEL: beta

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - mkdir c:\gopath
  - go install golang.org/x/tools/cmd/goimports@latest
  - go install golang.org/x/tools/cmd/gorename@latest
  - go install github.com/sqs/goreturns@latest
  - go install github.com/mdempsky/gocode@latest
  - go install github.com/alecthomas/gometalinter@latest
  - go install github.com/zmb3/gogetdoc@latest
  - go install github.com/zmb3/goaddimport@latest
  - go install github.com/rogpeppe/godef@latest
  - go install github.com/fatih/gomodifytags@latest
  - go install golang.org/x/tools/cmd/guru@latest
  - go install github.com/tpng/gopkgs@latest
  - go install github.com/ramya-rao-a/go-outline@latest

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
